/*
 * This file is auto-generated. Modifications will be lost.
 *
 * See https://android.googlesource.com/platform/bionic/+/master/libc/kernel/
 * for more information.
 */
#ifndef _UAPI_LINUX_DEV_ENERGYMODEL_H
#define _UAPI_LINUX_DEV_ENERGYMODEL_H
#define DEV_ENERGYMODEL_FAMILY_NAME "dev-energymodel"
#define DEV_ENERGYMODEL_FAMILY_VERSION 1
enum dev_energymodel_perf_state_flags {
  DEV_ENERGYMODEL_PERF_STATE_FLAGS_PERF_STATE_INEFFICIENT = 1,
};
enum dev_energymodel_perf_domain_flags {
  DEV_ENERGYMODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_MICROWATTS = 1,
  DEV_ENERGYMODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_SKIP_INEFFICIENCIES = 2,
  DEV_ENERGYMODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_ARTIFICIAL = 4,
};
enum {
  DEV_ENERGYMODEL_A_PERF_DOMAIN_PAD = 1,
  DEV_ENERGYMODEL_A_PERF_DOMAIN_PERF_DOMAIN_ID,
  DEV_ENERGYMODEL_A_PERF_DOMAIN_FLAGS,
  DEV_ENERGYMODEL_A_PERF_DOMAIN_CPUS,
  __DEV_ENERGYMODEL_A_PERF_DOMAIN_MAX,
  DEV_ENERGYMODEL_A_PERF_DOMAIN_MAX = (__DEV_ENERGYMODEL_A_PERF_DOMAIN_MAX - 1)
};
enum {
  DEV_ENERGYMODEL_A_PERF_TABLE_PERF_DOMAIN_ID = 1,
  DEV_ENERGYMODEL_A_PERF_TABLE_PERF_STATE,
  __DEV_ENERGYMODEL_A_PERF_TABLE_MAX,
  DEV_ENERGYMODEL_A_PERF_TABLE_MAX = (__DEV_ENERGYMODEL_A_PERF_TABLE_MAX - 1)
};
enum {
  DEV_ENERGYMODEL_A_PERF_STATE_PAD = 1,
  DEV_ENERGYMODEL_A_PERF_STATE_PERFORMANCE,
  DEV_ENERGYMODEL_A_PERF_STATE_FREQUENCY,
  DEV_ENERGYMODEL_A_PERF_STATE_POWER,
  DEV_ENERGYMODEL_A_PERF_STATE_COST,
  DEV_ENERGYMODEL_A_PERF_STATE_FLAGS,
  __DEV_ENERGYMODEL_A_PERF_STATE_MAX,
  DEV_ENERGYMODEL_A_PERF_STATE_MAX = (__DEV_ENERGYMODEL_A_PERF_STATE_MAX - 1)
};
enum {
  DEV_ENERGYMODEL_CMD_GET_PERF_DOMAINS = 1,
  DEV_ENERGYMODEL_CMD_GET_PERF_TABLE,
  DEV_ENERGYMODEL_CMD_PERF_DOMAIN_CREATED,
  DEV_ENERGYMODEL_CMD_PERF_DOMAIN_UPDATED,
  DEV_ENERGYMODEL_CMD_PERF_DOMAIN_DELETED,
  __DEV_ENERGYMODEL_CMD_MAX,
  DEV_ENERGYMODEL_CMD_MAX = (__DEV_ENERGYMODEL_CMD_MAX - 1)
};
#define DEV_ENERGYMODEL_MCGRP_EVENT "event"
#endif
